/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedGarcomRouteImport } from './routes/_authenticated/garcom'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedPedidosOnlineRouteImport } from './routes/_authenticated/pedidos-online'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as CardapioSlugRouteImport } from './routes/cardapio.$slug'
import { Route as AuthenticatedGarcomIndexRouteImport } from './routes/_authenticated/garcom/index'
import { Route as AuthenticatedGarcomMesaIdRouteImport } from './routes/_authenticated/garcom/mesa.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGarcomRoute = AuthenticatedGarcomRouteImport.update({
  id: '/garcom',
  path: '/garcom',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPedidosOnlineRoute =
  AuthenticatedPedidosOnlineRouteImport.update({
    id: '/pedidos-online',
    path: '/pedidos-online',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const CardapioSlugRoute = CardapioSlugRouteImport.update({
  id: '/cardapio/$slug',
  path: '/cardapio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGarcomIndexRoute =
  AuthenticatedGarcomIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGarcomRoute,
  } as any)
const AuthenticatedGarcomMesaIdRoute =
  AuthenticatedGarcomMesaIdRouteImport.update({
    id: '/mesa/$id',
    path: '/mesa/$id',
    getParentRoute: () => AuthenticatedGarcomRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/garcom': typeof AuthenticatedGarcomRouteWithChildren
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/pedidos-online': typeof AuthenticatedPedidosOnlineRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/cardapio/$slug': typeof CardapioSlugRoute
  '/garcom/': typeof AuthenticatedGarcomIndexRoute
  '/garcom/mesa/$id': typeof AuthenticatedGarcomMesaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/pedidos-online': typeof AuthenticatedPedidosOnlineRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/cardapio/$slug': typeof CardapioSlugRoute
  '/garcom': typeof AuthenticatedGarcomIndexRoute
  '/garcom/mesa/$id': typeof AuthenticatedGarcomMesaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/garcom': typeof AuthenticatedGarcomRouteWithChildren
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRoute
  '/_authenticated/pedidos-online': typeof AuthenticatedPedidosOnlineRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/cardapio/$slug': typeof CardapioSlugRoute
  '/_authenticated/garcom/': typeof AuthenticatedGarcomIndexRoute
  '/_authenticated/garcom/mesa/$id': typeof AuthenticatedGarcomMesaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/garcom'
    | '/pedidos'
    | '/pedidos-online'
    | '/relatorios'
    | '/cardapio/$slug'
    | '/garcom/'
    | '/garcom/mesa/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/pedidos'
    | '/pedidos-online'
    | '/relatorios'
    | '/cardapio/$slug'
    | '/garcom'
    | '/garcom/mesa/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/garcom'
    | '/_authenticated/pedidos'
    | '/_authenticated/pedidos-online'
    | '/_authenticated/relatorios'
    | '/cardapio/$slug'
    | '/_authenticated/garcom/'
    | '/_authenticated/garcom/mesa/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  CardapioSlugRoute: typeof CardapioSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/garcom': {
      id: '/_authenticated/garcom'
      path: '/garcom'
      fullPath: '/garcom'
      preLoaderRoute: typeof AuthenticatedGarcomRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pedidos-online': {
      id: '/_authenticated/pedidos-online'
      path: '/pedidos-online'
      fullPath: '/pedidos-online'
      preLoaderRoute: typeof AuthenticatedPedidosOnlineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/cardapio/$slug': {
      id: '/cardapio/$slug'
      path: '/cardapio/$slug'
      fullPath: '/cardapio/$slug'
      preLoaderRoute: typeof CardapioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/garcom/': {
      id: '/_authenticated/garcom/'
      path: '/'
      fullPath: '/garcom/'
      preLoaderRoute: typeof AuthenticatedGarcomIndexRouteImport
      parentRoute: typeof AuthenticatedGarcomRoute
    }
    '/_authenticated/garcom/mesa/$id': {
      id: '/_authenticated/garcom/mesa/$id'
      path: '/mesa/$id'
      fullPath: '/garcom/mesa/$id'
      preLoaderRoute: typeof AuthenticatedGarcomMesaIdRouteImport
      parentRoute: typeof AuthenticatedGarcomRoute
    }
  }
}

interface AuthenticatedGarcomRouteChildren {
  AuthenticatedGarcomIndexRoute: typeof AuthenticatedGarcomIndexRoute
  AuthenticatedGarcomMesaIdRoute: typeof AuthenticatedGarcomMesaIdRoute
}

const AuthenticatedGarcomRouteChildren: AuthenticatedGarcomRouteChildren = {
  AuthenticatedGarcomIndexRoute: AuthenticatedGarcomIndexRoute,
  AuthenticatedGarcomMesaIdRoute: AuthenticatedGarcomMesaIdRoute,
}

const AuthenticatedGarcomRouteWithChildren =
  AuthenticatedGarcomRoute._addFileChildren(AuthenticatedGarcomRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedGarcomRoute: typeof AuthenticatedGarcomRouteWithChildren
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRoute
  AuthenticatedPedidosOnlineRoute: typeof AuthenticatedPedidosOnlineRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedGarcomRoute: AuthenticatedGarcomRouteWithChildren,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRoute,
  AuthenticatedPedidosOnlineRoute: AuthenticatedPedidosOnlineRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  CardapioSlugRoute: CardapioSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
